# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='utils.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0butils.proto\"4\n\rGeoCoordinate\x12\x10\n\x08latitude\x18\x01 \x02(\x01\x12\x11\n\tlongitude\x18\x02 \x02(\x01')
)




_GEOCOORDINATE = _descriptor.Descriptor(
  name='GeoCoordinate',
  full_name='GeoCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='GeoCoordinate.latitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='GeoCoordinate.longitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['GeoCoordinate'] = _GEOCOORDINATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeoCoordinate = _reflection.GeneratedProtocolMessageType('GeoCoordinate', (_message.Message,), dict(
  DESCRIPTOR = _GEOCOORDINATE,
  __module__ = 'utils_pb2'
  # @@protoc_insertion_point(class_scope:GeoCoordinate)
  ))
_sym_db.RegisterMessage(GeoCoordinate)


# @@protoc_insertion_point(module_scope)
